server:
  port: 8083

spring:
  application:
    name: batch

  eureka:
    instance:
      instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    client:
      service-url:
        default-zone: http://localhost:8761/eureka
