server:
  port: 8084
  servlet:
    context-path: /fundings

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: funding

  config:
    import: application-funding-dev.yml, application-funding-prod.yml, application-funding-local.yml

  datasource:
    url: jdbc:mysql://localhost:3306/mooding?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mooding
    password: mooding84595

  eureka:
    instance:
      instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    client:
      service-url:
        default-zone: http://localhost:8761/eureka

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

kafka:
  topics:
    test: order
    payment: refund
  consumer:
    group-id: my-group

grpc:
  client:
    user:
      address: 'discovery:///USER'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    payment:
      address: 'discovery:///PAYMENT'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  config:
    classpath:
      logback.xml

redis:
  host: localhost
  port: 6379

swagger:
  host: localhost:8084