server:
  port: 8084

spring:
  application:
    name: funding

  config:
    import: application-funding-local.yml

  eureka:
    client:
      service-url:
        default-zone: http://localhost:8761/eureka
