server:
  port: 8084
  servlet:
    context-path: /fundings

spring:
  application:
    name: funding

  config:
    import: application-funding-local.yml

  eureka:
    client:
      service-url:
        default-zone: http://localhost:8761/eureka

  kafka:
    bootstrap-servers: localhost:9092

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

kafka:
  topics:
    test: order
  consumer:
    group-id: my-group

grpc:
  client:
    user:
      address: 'discovery:///USER'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: trace