server:
  port: 8084
  servlet:
    context-path: /fundings

spring:
  application:
    name: funding

  config:
    import: application-funding-local.yml, application-funding-dev.yml, application-funding-prod.yml,

  eureka:
    instance:
      instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    client:
      service-url:
        default-zone: http://localhost:8761/eureka

  kafka:
    bootstrap-servers: j10c204.p.ssafy.io:9092

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

kafka:
  topics:
    test: order
  consumer:
    group-id: my-group

grpc:
  client:
    user:
      address: 'discovery:///USER'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    payment:
      address: 'discovery:///PAYMENT'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  config:
    classpath:
      logback.xml