server:
  port: 8086
  servlet:
    context-path: /users

spring:
  application:
    name: user

  config:
    import: application-user-local.yml, application-user-prod.yml

  eureka:
    instance:
      instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    client:
      service-url:
        default-zone: http://localhost:8761/eureka

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

security:
  jwt:
    access-expiration-time: 2592000000
    refresh-expiration-time: 2592000000

grpc:
  server:
    port: 9999