spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://j10c204.p.ssafy.io:3306/mooding?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mooding
    password: mooding84595

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
swagger:
  host: localhost:8086

redis:
  host: localhost
  port: 6379

oauth2:
  provider:
    naver:
      client-id: i6wNtvL6tR5n9p0ERkNi
      redirect-uri: http://localhost:5174/login/naver
      token-uri: https://nid.naver.com/oauth2.0/token
      user-info: https://openapi.naver.com/v1/nid/me
      client-secret: DNolvvC9x8
      unlink-uri: https://nid.naver.com/oauth2.0/token

security:
  jwt:
    secret-key: c3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwK