server:
  port: 8086

spring:
  application:
    name: user

  config:
    import: application-user-local.yml

  eureka:
    client:
      service-url:
        default-zone: http://localhost:8761/eureka

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher