server:
  port: 8086
  servlet:
    context-path: /users

spring:
  application:
    name: user

  config:
    import: application-user-local.yml, application-user-prod.yml

  eureka:
    instance:
      instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    client:
      service-url:
        default-zone: http://localhost:8761/eureka

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://localhost:3306/mooding?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mooding
    password: mooding84595

security:
  jwt:
    access-expiration-time: 2592000000
    refresh-expiration-time: 2592000000
    secret-key: c3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwK

grpc:
  server:
    port: 9999

redis:
  host: localhost
  port: 6379

oauth2:
  provider:
    naver:
      client-id: i6wNtvL6tR5n9p0ERkNi
      redirect-uri: http://localhost:5174/login/naver
      token-uri: https://nid.naver.com/oauth2.0/token
      user-info: https://openapi.naver.com/v1/nid/me
      client-secret: DNolvvC9x8
      unlink-uri: https://nid.naver.com/oauth2.0/token

swagger:
  host: localhost:8086