server:
  port: 8082

spring:
  application:
    name: payment

  config:
    import: application-payment-local.yml

  eureka:
    client:
      service-url:
        default-zone: http://localhost:8761/eureka