server:
  port: 8085

spring:
  application:
    name: reservation

  config:
    import: application-reservation-local.yml

  eureka:
    client:
      service-url:
        default-zone: http://localhost:8761/eureka

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher