server:
  port: 8085
  servlet:
    context-path: /reservations


spring:
  application:
    name: reservation

  config:
    import: application-reservation-local.yml, application-reservation-prod.yml

  datasource:
    url: jdbc:mysql://localhost:3306/mooding?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mooding
    password: mooding84595

  eureka:
    instance:
      instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    client:
      service-url:
        default-zone: http://localhost:8761/eureka

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher