spring:
  config:
    activate:
      on-profile: prod
      
  datasource:
    url: jdbc:mysql://j10c204.p.ssafy.io:3306/mooding?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mooding
    password: mooding84595

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

swagger:
  host: j10C204.p.ssafy.io:8085

redis:
  host: j10C204.p.ssafy.io
  port: 6379