services:
  spring-boot:
    restart: 'on-failure'
    build:
      dockerfile: Dockerfile
      args:
        PROFILE: prod
    container_name: 'discovery-prod'
    ports:
      - 8761:8761
#    networks:
#      - mooding_network
#
#networks:
#  mooding_network:
