services:
  spring-boot:
    restart: 'on-failure'
    build:
      dockerfile: Dockerfile
      args:
        PROFILE: local
    container_name: 'discovery-local'
    ports:
      - 8761:8761
    networks:
      - mooding_network

networks:
  mooding_network: