server:
  port: 8082
  servlet:
    context-path: /payments

swagger:
  host: localhost:8082

toss:
  secret-key: ${TOSS_PAYMENTS_KEY:test_sk_GePWvyJnrKvL90vz6y9EVgLzN97E}
  mid: ${TOSS_MID:gosroc9mwo}

feign:
  toss:
    url : https://api.tosspayments.com

kafka:
  topics:
    test: order
    payment: refund

spring:
  application:
    name: payment
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

grpc:
  server:
    port: 9998

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/payment?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: payment
    password: payment84595

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group

    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

#  swagger:
#    host: localhost:8082



---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://j10c204.p.ssafy.io:3306/payment?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: payment
    password: payment84595

  kafka:
    bootstrap-servers: j10c204.p.ssafy.io:9092
    consumer:
      group-id: my-group

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

swagger:
  host: j10C204.p.ssafy.io:8082

toss:
  secret-key: ${TOSS_PAYMENTS_KEY:test_sk_GePWvyJnrKvL90vz6y9EVgLzN97E}
  mid : ${TOSS_MID:gosroc9mwo}

redis:
  host: j10C204.p.ssafy.io
  port: 6379