services:
  spring-boot:
    restart: 'on-failure'
    build:
      dockerfile: Dockerfile
      args:
        PROFILE: dev
    container_name: 'gateway-dev'
    ports:
      - 8081:8081
    networks:
      - mooding_network

networks:
  mooding_network:
